apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: api
  namespace: configconnector-resources
spec:
  name: "{{ .Values.api.domain }}."
  type: A
  ttl: 300
  managedZoneRef:
    external: "{{ .Values.dns.zone }}"
  rrdatasRefs:
  - name: api
    kind: ComputeAddress
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: api
  namespace: configconnector-resources
spec:
  location: global
  resourceID: isidro-api
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: mattermost
  namespace: configconnector-resources
spec:
  name: "{{ .Values.mattermost.domain }}."
  type: A
  ttl: 300
  managedZoneRef:
    external: "{{ .Values.dns.zone }}"
  rrdatasRefs:
  - name: mattermost
    kind: ComputeAddress
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: mattermost
  namespace: configconnector-resources
spec:
  location: global
  resourceID: isidro-mattermost