apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: build
build:
  artifacts:
  - image: us.gcr.io/GOOGLE_PROJECT/isidro/deployer/github
    context: deployer/github
    kaniko:
      cache: {}
    hooks:
      after:
      - command: ["bash", "-c", "./skaffold-binauthz.sh $SKAFFOLD_IMAGE"]
  - image: us.gcr.io/GOOGLE_PROJECT/isidro/gatekeeper
    context: gatekeeper
    kaniko:
      cache: {}
    hooks:
      after:
      - command: ["bash", "-c", "./skaffold-binauthz.sh $SKAFFOLD_IMAGE"]
  - image: us.gcr.io/GOOGLE_PROJECT/isidro/orchestration
    context: orchestration
    kaniko:
      cache: {}
    hooks:
      after:
      - command: ["bash", "-c", "./skaffold-binauthz.sh $SKAFFOLD_IMAGE"]
  - image: us.gcr.io/GOOGLE_PROJECT/isidro/repeater
    context: repeater
    kaniko:
      cache: {}
    hooks:
      after:
      - command: ["bash", "-c", "./skaffold-binauthz.sh $SKAFFOLD_IMAGE"]
  - image: us.gcr.io/GOOGLE_PROJECT/isidro/responder
    context: responder
    kaniko:
      cache: {}
    hooks:
      after:
      - command: ["bash", "-c", "./skaffold-binauthz.sh $SKAFFOLD_IMAGE"]
  - image: us.gcr.io/GOOGLE_PROJECT/isidro/tasks
    context: tasks
    kaniko:
      cache: {}
    hooks:
      after:
      - command: ["bash", "-c", "./skaffold-binauthz.sh $SKAFFOLD_IMAGE"]
  googleCloudBuild:
    timeout: 3600s
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: build-nlp
build:
  artifacts:
  - image: us.gcr.io/GOOGLE_PROJECT/isidro/keywords
    context: keywords
    kaniko:
      cache: {}
    hooks:
      after:
      - command: ["bash", "-c", "./skaffold-binauthz.sh $SKAFFOLD_IMAGE"]
  googleCloudBuild:
    timeout: 3600s
    machineType: E2_HIGHCPU_32
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deploy-mattermost
deploy:
  kubeContext: isidro-us
  helm:
    releases:
    - name: mattermost
      remoteChart: mattermost/mattermost-team-edition
      version: 6.5.0
      createNamespace: true
      namespace: mattermost
      setValues:
        deploymentStrategy.type: Recreate
        securityContext.fsGroup: "2000"
        mysql.mysqlUser: isidro
        mysql.mysqlPassword: isidro
        mysql.persistence.storageClass: isidro-storage
        persistence.data.storageClass: isidro-storage
        persistence.plugins.storageClass: isidro-storage
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deploy-us
requires:
- configs: ["build-nlp", "build"]
deploy:
  kubeContext: isidro-us
  helm:
    releases:
    - name: isidro
      chartPath: chart
      skipBuildDependencies: true
      createNamespace: true
      namespace: isidro
      setValues:
        project: GOOGLE_PROJECT
        mattermost.domain: MATTERMOST_DOMAIN
        mattermost.accessToken: "1234567890"
        mattermost.verificationToken: "1234567890"
        orchestration.greeting: "Hello!"
        deployer.github.token: "1234567890"
      artifactOverrides:
        deployer.github.image: us.gcr.io/GOOGLE_PROJECT/isidro/deployer/github
        gatekeeper.image: us.gcr.io/GOOGLE_PROJECT/isidro/gatekeeper
        keywords.image: us.gcr.io/GOOGLE_PROJECT/isidro/keywords
        orchestration.image: us.gcr.io/GOOGLE_PROJECT/isidro/orchestration
        repeater.image: us.gcr.io/GOOGLE_PROJECT/isidro/repeater
        responder.image: us.gcr.io/GOOGLE_PROJECT/isidro/responder
        tasks.image: us.gcr.io/GOOGLE_PROJECT/isidro/tasks
      imageStrategy:
        helm: {}
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deploy-fi
requires:
- configs: ["build-nlp", "build"]
deploy:
  kubeContext: isidro-fi
  helm:
    releases:
    - name: isidro
      chartPath: chart
      skipBuildDependencies: true
      createNamespace: true
      namespace: isidro
      setValues:
        project: GOOGLE_PROJECT
        region: europe-north1
        zones[0]: "europe-north1-a"
        zones[1]: "europe-north1-b"
        zones[2]: "europe-north1-c"
        mattermost.domain: MATTERMOST_DOMAIN
        mattermost.accessToken: "1234567890"
        mattermost.verificationToken: "1234567890"
        orchestration.greeting: "Bonjour!"
        deployer.github.token: "1234567890"
      artifactOverrides:
        deployer.github.image: us.gcr.io/GOOGLE_PROJECT/isidro/deployer/github
        gatekeeper.image: us.gcr.io/GOOGLE_PROJECT/isidro/gatekeeper
        keywords.image: us.gcr.io/GOOGLE_PROJECT/isidro/keywords
        orchestration.image: us.gcr.io/GOOGLE_PROJECT/isidro/orchestration
        repeater.image: us.gcr.io/GOOGLE_PROJECT/isidro/repeater
        responder.image: us.gcr.io/GOOGLE_PROJECT/isidro/responder
        tasks.image: us.gcr.io/GOOGLE_PROJECT/isidro/tasks
      imageStrategy:
        helm: {}
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deploy-br
requires:
- configs: ["build-nlp", "build"]
deploy:
  kubeContext: isidro-br
  helm:
    releases:
    - name: isidro
      chartPath: chart
      skipBuildDependencies: true
      createNamespace: true
      namespace: isidro
      setValues:
        project: GOOGLE_PROJECT
        region: southamerica-east1
        zones[0]: "southamerica-east1-a"
        zones[1]: "southamerica-east1-b"
        zones[2]: "southamerica-east1-c"
        mattermost.domain: MATTERMOST_DOMAIN
        mattermost.accessToken: "1234567890"
        mattermost.verificationToken: "1234567890"
        orchestration.greeting: "Olá!"
        deployer.github.token: "1234567890"
      artifactOverrides:
        deployer.github.image: us.gcr.io/GOOGLE_PROJECT/isidro/deployer/github
        gatekeeper.image: us.gcr.io/GOOGLE_PROJECT/isidro/gatekeeper
        keywords.image: us.gcr.io/GOOGLE_PROJECT/isidro/keywords
        orchestration.image: us.gcr.io/GOOGLE_PROJECT/isidro/orchestration
        repeater.image: us.gcr.io/GOOGLE_PROJECT/isidro/repeater
        responder.image: us.gcr.io/GOOGLE_PROJECT/isidro/responder
        tasks.image: us.gcr.io/GOOGLE_PROJECT/isidro/tasks
      imageStrategy:
        helm: {}
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deploy-networking-1
deploy:
  kubeContext: isidro-config
  kubectl:
    manifests:
    - "networking/configconnector-operator.yaml"
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deploy-networking-2
requires:
- configs: ["deploy-networking-1"]
deploy:
  kubeContext: isidro-config
  kubectl:
    manifests:
    - "networking/configconnector-setup.yaml"
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deploy-networking-3
requires:
- configs: ["deploy-networking-2"]
deploy:
  kubeContext: isidro-config
  kubectl:
    manifests:
    - "networking/certbot.yaml"
    - "networking/dns.yaml"
    - "networking/multiclusteringress.yaml"
    - "networking/multiclusterservices.yaml"
    - "networking/namespace.yaml"